<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>LostAndDivine.Launcher</RootNamespace>
    <AssemblyName>LostAndDivine.Launcher</AssemblyName>
    <ApplicationIcon>..\LostAndDivine.ClientMonoGame\Icon_Game.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LostAndDivine.Shared\LostAndDivine.Shared.csproj" />
  </ItemGroup>

</Project>
