<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>LostAndDivine.Editor</RootNamespace>
    <AssemblyName>LostAndDivine.Editor</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LostAndDivine.Shared\LostAndDivine.Shared.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

</Project>